#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/lge/winglm

PRODUCT_COPY_FILES += \
    vendor/lge/winglm/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/lge/winglm/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/lge/winglm/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/lge/winglm/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/lge/winglm/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/lge/winglm/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/lge/winglm/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/lge/winglm/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/lge/winglm/proprietary/vendor/etc/camera/auxpackagelist.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/auxpackagelist.txt \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/10_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/10_cine-max.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/10_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/10_cine-min.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/10_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/10_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/10_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/10_vignette.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/11_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/11_cine-max.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/11_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/11_cine-min.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/11_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/11_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/11_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/11_vignette.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/12_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/12_cine-max.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/12_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/12_cine-min.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/12_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/12_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/13_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/13_cine-max.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/13_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/13_cine-min.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/13_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/13_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/14_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/14_cine-max.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/14_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/14_cine-min.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/14_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/14_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/15_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/15_cine-max.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/15_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/15_cine-min.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/15_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/15_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/16_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/16_cine-max.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/16_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/16_cine-min.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/16_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/16_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/17_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/17_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/18_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/18_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/19_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/19_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/1_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/1_cine-max.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/1_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/1_cine-min.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/1_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/1_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/1_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/1_vignette.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/20_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/20_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/21_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/21_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/2_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/2_cine-max.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/2_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/2_cine-min.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/2_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/2_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/2_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/2_vignette.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/3_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/3_cine-max.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/3_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/3_cine-min.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/3_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/3_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/3_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/3_vignette.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/4_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/4_cine-max.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/4_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/4_cine-min.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/4_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/4_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/4_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/4_vignette.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/5_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/5_cine-max.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/5_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/5_cine-min.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/5_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/5_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/5_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/5_vignette.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/6_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/6_cine-max.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/6_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/6_cine-min.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/6_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/6_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/6_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/6_vignette.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/7_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/7_cine-max.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/7_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/7_cine-min.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/7_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/7_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/7_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/7_vignette.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/8_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/8_cine-max.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/8_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/8_cine-min.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/8_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/8_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/8_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/8_vignette.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/9_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/9_cine-max.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/9_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/9_cine-min.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/9_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/9_cine_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/9_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/9_vignette.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/cinema/cine_min_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/cine_min_10.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/film/0_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/0_film.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/film/10_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/10_film.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/film/1_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/1_film.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/film/2_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/2_film.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/film/3_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/3_film.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/film/4_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/4_film.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/film/5_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/5_film.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/film/6_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/6_film.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/film/7_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/7_film.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/film/8_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/8_film.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/film/9_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/9_film.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/food/1_food.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/food/1_food.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/iqm/ai_checker_graph.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/iqm/ai_checker_graph.dlc \
    vendor/lge/winglm/proprietary/vendor/etc/camera/iqm/fc4_awb.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/iqm/fc4_awb.dlc \
    vendor/lge/winglm/proprietary/vendor/etc/camera/iqm/gender_detection_graph.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/iqm/gender_detection_graph.dlc \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/capture/Grooming_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Grooming_c.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/capture/Idol_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Idol_c.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/capture/Iu_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Iu_c.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/capture/Japanese_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Japanese_c.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/capture/Luxury_eye_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Luxury_eye_c.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/capture/Luxury_lip_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Luxury_lip_c.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/capture/Natural_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Natural_c.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/capture/Rose_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Rose_c.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/capture/Teen_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Teen_c.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/capture/Wedding_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Wedding_c.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/preview/Grooming_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Grooming_p.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/preview/Idol_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Idol_p.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/preview/Iu_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Iu_p.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/preview/Japanese_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Japanese_p.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/preview/Luxury_eye_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Luxury_eye_p.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/preview/Luxury_lip_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Luxury_lip_p.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/preview/Natural_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Natural_p.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/preview/Rose_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Rose_p.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/preview/Teen_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Teen_p.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/preview/Wedding_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Wedding_p.cng \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_10_grooming_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_10_grooming_h_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_10_grooming_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_10_grooming_s_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_1_natural_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_1_natural_h_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_1_natural_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_1_natural_s_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_2_rose_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_2_rose_h_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_2_rose_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_2_rose_s_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_3_luxury_eyes_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_3_luxury_eyes_h_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_3_luxury_eyes_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_3_luxury_eyes_s_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_4_teen_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_4_teen_h_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_4_teen_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_4_teen_s_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_5_luxury_lip_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_5_luxury_lip_h_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_5_luxury_lip_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_5_luxury_lip_s_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_6_idol_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_6_idol_h_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_6_idol_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_6_idol_s_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_7_wedding_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_7_wedding_h_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_7_wedding_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_7_wedding_s_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_8_iu_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_8_iu_h_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_8_iu_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_8_iu_s_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_9_japanese_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_9_japanese_h_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_9_japanese_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_9_japanese_s_325x400.BGR32 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/outfocus/deepportrait_snapshot.dlce:$(TARGET_COPY_OUT_VENDOR)/etc/camera/outfocus/deepportrait_snapshot.dlce \
    vendor/lge/winglm/proprietary/vendor/etc/camera/portraitlight/Back_filter.NV21:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portraitlight/Back_filter.NV21 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/portraitlight/Gradation.NV21:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portraitlight/Gradation.NV21 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/portraitlight/Pink.NV21:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portraitlight/Pink.NV21 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/portraitlight/Texture.NV21:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portraitlight/Texture.NV21 \
    vendor/lge/winglm/proprietary/vendor/etc/camera/selfie/1_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/1_selfie.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/selfie/2_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/2_selfie.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/selfie/3_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/3_selfie.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/selfie/4_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/4_selfie.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/selfie/5_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/5_selfie.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/selfie/6_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/6_selfie.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/selfie/7_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/7_selfie.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/selfie/8_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/8_selfie.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/selfie/9_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/9_selfie.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/0_smartcam.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/0_smartcam.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/10_smartcam_food.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/10_smartcam_food.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/11_smartcam_food.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/11_smartcam_food.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/12_smartcam_food.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/12_smartcam_food.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/13_1_H_smartcam_person_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/13_1_H_smartcam_person_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/13_2_L_smartcam_person_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/13_2_L_smartcam_person_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/13_smartcam_person_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/13_smartcam_person_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/14_smartcam_person_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/14_smartcam_person_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/15_smartcam_person_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/15_smartcam_person_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/16_smartcam_person_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/16_smartcam_person_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/17_1_H_smartcam_landscape.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/17_1_H_smartcam_landscape.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/17_2_L_smartcam_landscape.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/17_2_L_smartcam_landscape.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/17_smartcam_landscape.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/17_smartcam_landscape.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/18_smartcam_landscape.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/18_smartcam_landscape.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/19_smartcam_landscape.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/19_smartcam_landscape.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/1_1_H_smartcam_pet.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/1_1_H_smartcam_pet.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/1_2_L_smartcam_pet.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/1_2_L_smartcam_pet.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/1_smartcam_pet.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/1_smartcam_pet.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/20_smartcam_landscape.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/20_smartcam_landscape.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/21_1_H_smartcam_sunset_sunrise.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/21_1_H_smartcam_sunset_sunrise.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/21_2_L_smartcam_sunset_sunrise.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/21_2_L_smartcam_sunset_sunrise.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/21_smartcam_sunset_sunrise.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/21_smartcam_sunset_sunrise.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/22_smartcam_sunset_sunrise.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/22_smartcam_sunset_sunrise.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/23_smartcam_sunset_sunrise.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/23_smartcam_sunset_sunrise.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/24_smartcam_sunset_sunrise.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/24_smartcam_sunset_sunrise.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/25_smartcam_flower.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/25_smartcam_flower.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/26_smartcam_flower.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/26_smartcam_flower.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/27_smartcam_flower.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/27_smartcam_flower.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/28_smartcam_flower.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/28_smartcam_flower.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/29_1_H_smartcam_people_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/29_1_H_smartcam_people_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/29_2_L_smartcam_people_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/29_2_L_smartcam_people_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/29_smartcam_people_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/29_smartcam_people_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/2_smartcam_pet.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/2_smartcam_pet.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/30_smartcam_people_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/30_smartcam_people_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/31_smartcam_people_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/31_smartcam_people_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/32_smartcam_people_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/32_smartcam_people_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/33_1_H_smartcam_baby_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/33_1_H_smartcam_baby_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/33_2_L_smartcam_baby_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/33_2_L_smartcam_baby_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/33_smartcam_baby_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/33_smartcam_baby_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/34_smartcam_baby_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/34_smartcam_baby_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/35_smartcam_baby_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/35_smartcam_baby_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/36_smartcam_baby_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/36_smartcam_baby_rear.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/37_smartcam_animal.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/37_smartcam_animal.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/38_smartcam_animal.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/38_smartcam_animal.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/39_smartcam_animal.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/39_smartcam_animal.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/3_smartcam_pet.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/3_smartcam_pet.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/40_smartcam_animal.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/40_smartcam_animal.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/41_1_H_smartcam_beverage.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/41_1_H_smartcam_beverage.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/41_2_L_smartcam_beverage.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/41_2_L_smartcam_beverage.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/41_smartcam_beverage.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/41_smartcam_beverage.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/42_smartcam_beverage.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/42_smartcam_beverage.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/43_smartcam_beverage.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/43_smartcam_beverage.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/44_smartcam_beverage.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/44_smartcam_beverage.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/45_smartcam_fruit.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/45_smartcam_fruit.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/46_smartcam_fruit.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/46_smartcam_fruit.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/47_smartcam_fruit.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/47_smartcam_fruit.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/48_smartcam_fruit.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/48_smartcam_fruit.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/49_smartcam_snow.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/49_smartcam_snow.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/4_smartcam_pet.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/4_smartcam_pet.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/50_smartcam_snow.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/50_smartcam_snow.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/51_smartcam_snow.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/51_smartcam_snow.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/52_smartcam_snow.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/52_smartcam_snow.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/53_1_H_smartcam_sky.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/53_1_H_smartcam_sky.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/53_2_L_smartcam_sky.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/53_2_L_smartcam_sky.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/53_smartcam_sky.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/53_smartcam_sky.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/54_smartcam_sky.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/54_smartcam_sky.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/55_smartcam_sky.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/55_smartcam_sky.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/56_smartcam_sky.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/56_smartcam_sky.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/57_smartcam_beach.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/57_smartcam_beach.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/58_smartcam_beach.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/58_smartcam_beach.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/59_smartcam_beach.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/59_smartcam_beach.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/5_1_H_smartcam_city.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/5_1_H_smartcam_city.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/5_2_L_smartcam_city.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/5_2_L_smartcam_city.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/5_smartcam_city.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/5_smartcam_city.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/60_smartcam_beach.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/60_smartcam_beach.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/61_smartcam_lowlight.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/61_smartcam_lowlight.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/62_smartcam_lowlight.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/62_smartcam_lowlight.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/63_smartcam_lowlight.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/63_smartcam_lowlight.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/64_smartcam_lowlight.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/64_smartcam_lowlight.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/65_1_H_smartcam_person_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/65_1_H_smartcam_person_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/65_2_L_smartcam_person_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/65_2_L_smartcam_person_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/65_smartcam_person_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/65_smartcam_person_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/66_smartcam_person_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/66_smartcam_person_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/67_smartcam_person_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/67_smartcam_person_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/68_smartcam_person_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/68_smartcam_person_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/69_1_H_smartcam_people_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/69_1_H_smartcam_people_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/69_2_L_smartcam_people_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/69_2_L_smartcam_people_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/69_smartcam_people_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/69_smartcam_people_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/6_smartcam_city.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/6_smartcam_city.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/70_smartcam_people_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/70_smartcam_people_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/71_smartcam_people_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/71_smartcam_people_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/72_smartcam_people_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/72_smartcam_people_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/73_1_H_smartcam_baby_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/73_1_H_smartcam_baby_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/73_2_L_smartcam_baby_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/73_2_L_smartcam_baby_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/73_smartcam_baby_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/73_smartcam_baby_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/74_smartcam_baby_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/74_smartcam_baby_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/75_smartcam_baby_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/75_smartcam_baby_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/76_smartcam_baby_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/76_smartcam_baby_front.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/7_smartcam_city.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/7_smartcam_city.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/8_smartcam_city.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/8_smartcam_city.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/91_smartcam_basic_01.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/91_smartcam_basic_01.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/92_smartcam_basic_02.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/92_smartcam_basic_02.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/93_smartcam_basic_03.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/93_smartcam_basic_03.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/94_smartcam_basic_04.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/94_smartcam_basic_04.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/9_1_H_smartcam_food.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/9_1_H_smartcam_food.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/9_2_L_smartcam_food.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/9_2_L_smartcam_food.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/smartcam/9_smartcam_food.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/9_smartcam_food.dat \
    vendor/lge/winglm/proprietary/vendor/etc/camera/vnr/SJ_VideoNR_LUT.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vnr/SJ_VideoNR_LUT.bin \
    vendor/lge/winglm/proprietary/vendor/etc/display/advanced_sf_offsets.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/advanced_sf_offsets.xml \
    vendor/lge/winglm/proprietary/vendor/etc/init/ipa_fws.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipa_fws.rc \
    vendor/lge/winglm/proprietary/vendor/etc/init/vendor.lge.hardware.motor@1.0-service-popupcam.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.lge.hardware.motor@1.0-service-popupcam.rc \
    vendor/lge/winglm/proprietary/vendor/etc/init/vendor.lge.hardware.sensors.devicecontext@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.lge.hardware.sensors.devicecontext@1.0-service.rc \
    vendor/lge/winglm/proprietary/vendor/etc/ltm_config_RM692C9_cmd_mode_dsc_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ltm_config_RM692C9_cmd_mode_dsc_dsi_panel.xml \
    vendor/lge/winglm/proprietary/vendor/etc/ltm_config_SW43103_cmd_mode_dsc_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ltm_config_SW43103_cmd_mode_dsc_dsi_panel.xml \
    vendor/lge/winglm/proprietary/vendor/etc/qdcm_calib_data_RM692C9_cmd_mode_dsc_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_RM692C9_cmd_mode_dsc_dsi_panel.xml \
    vendor/lge/winglm/proprietary/vendor/etc/qdcm_calib_data_SW43103_cmd_mode_dsc_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_SW43103_cmd_mode_dsc_dsi_panel.xml \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/descriptor.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/descriptor.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/nanopb.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/nanopb.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_accel.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_accel.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_accel_cal.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_accel_cal.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_activity_recognition.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_activity_recognition.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_ambient_light.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_ambient_light.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_ambient_temperature.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_ambient_temperature.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_amd.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_amd.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_aont.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_aont.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_basic_gestures.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_basic_gestures.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_bring_to_ear.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_bring_to_ear.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_cal.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_cal.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_client.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_client.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_cmc.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_cmc.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_da_test.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_da_test.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_device_context.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_device_context.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_device_mode.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_device_mode.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_device_orient.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_device_orient.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_diag.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_diag.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_diag_sensor.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_diag_sensor.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_direct_channel.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_direct_channel.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_dpc.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_dpc.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_ext_svc.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_ext_svc.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_facing.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_facing.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_fmv.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_fmv.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_formatter.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_formatter.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_formatter_notify.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_formatter_notify.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_fw.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_fw.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_game_rv.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_game_rv.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_geomag_rv.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_geomag_rv.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_gravity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_gravity.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_gyro.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_gyro.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_gyro_cal.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_gyro_cal.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_gyro_rot_matrix.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_gyro_rot_matrix.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_hall.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_hall.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_hall_distance.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_hall_distance.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_heart_beat.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_heart_beat.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_heart_rate.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_heart_rate.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_highg.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_highg.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_hinge_angle.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_hinge_angle.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_humidity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_humidity.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_knock_on_proximity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_knock_on_proximity.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_lg_airtouch_wakeup_proximity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_lg_airtouch_wakeup_proximity.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_lg_filtered_pressure.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_lg_filtered_pressure.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_lg_gated_gyro.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_lg_gated_gyro.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_lg_health_activity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_lg_health_activity.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_lg_pam.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_lg_pam.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_lg_tof_wakeup_proximity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_lg_tof_wakeup_proximity.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_lgpickup.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_lgpickup.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_lowg.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_lowg.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_mag.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_mag.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_mag_cal.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_mag_cal.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_motion_accel.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_motion_accel.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_oem1.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_oem1.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_offbody_detect.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_offbody_detect.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_pd_algo.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_pd_algo.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_pedometer.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_pedometer.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_pedometer_wrist.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_pedometer_wrist.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_physical_driver_access_test.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_physical_driver_access_test.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_physical_sensor_test.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_physical_sensor_test.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_pose_6dof.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_pose_6dof.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_ppg.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_ppg.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_pressure.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_pressure.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_proximity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_proximity.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_psmd.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_psmd.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_registry.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_registry.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_resampler.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_resampler.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_rgb.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_rgb.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_rmd.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_rmd.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_rotv.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_rotv.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_sar.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_sar.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_sensor_temperature.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_sensor_temperature.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_sig_motion.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_sig_motion.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_std.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_std.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_std_event_gated_sensor.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_std_event_gated_sensor.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_std_sensor.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_std_sensor.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_std_type.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_std_type.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_step_detect.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_step_detect.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_suid.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_suid.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_thermopile.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_thermopile.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_thresh.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_thresh.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_threshold.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_threshold.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_tilt.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_tilt.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_tilt_to_wake.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_tilt_to_wake.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_ultra_violet.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_ultra_violet.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_virtual_proximity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_virtual_proximity.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_wakeup_light.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_wakeup_light.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/proto/sns_wrist_tilt_gesture.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_wrist_tilt_gesture.proto \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/ak991x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/ak991x_dri_0.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/ak991x_dri_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/ak991x_dri_1.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/ak997x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/ak997x_dri_0.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/apds9159.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/apds9159.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/apds9169.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/apds9169.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/default_sensors.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/icm4x6xx_0.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/icm4x6xx_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/icm4x6xx_1.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/icp101xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/icp101xx_0.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/lito_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/lito_ak991x_0.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/lito_ak991x_0_rev0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/lito_ak991x_0_rev0.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/lito_ak991x_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/lito_ak991x_1.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/lito_ak991x_1_rev0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/lito_ak991x_1_rev0.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/lito_ak997x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/lito_ak997x_0.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/lito_apds9159.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/lito_apds9159.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/lito_apds9159_reva.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/lito_apds9159_reva.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/lito_apds9169.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/lito_apds9169.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/lito_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/lito_icm4x6xx_0.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/lito_icm4x6xx_0_rev0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/lito_icm4x6xx_0_rev0.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/lito_icm4x6xx_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/lito_icm4x6xx_1.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/lito_icm4x6xx_1_rev0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/lito_icm4x6xx_1_rev0.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/lito_icp101xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/lito_icp101xx_0.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_amd.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_amd_sw_disabled.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_amd_sw_enabled.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_aont.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_basic_gestures.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_bring_to_ear.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_ccd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_ccd.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_ccd_v2_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_ccd_v2_walk.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_ccd_v3_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_ccd_v3_walk.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_cm.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_dae.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_device_orient.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_diag_filter.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_distance_bound.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_dpc.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_facing.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_fmv.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_geomag_rv.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_gyro_cal.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_heart_rate.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_lg_filtered_pressure.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_lg_filtered_pressure.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_lg_gated_gyro.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_lg_gated_gyro.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_mag_cal.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_mag_cal_legacy.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_multishake.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_pedometer.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_rmd.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_rotv.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_smd.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt_sw_disabled.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt_sw_enabled.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt_to_wake.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_window_orientation.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_window_orientation.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_wrist_pedo.json \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/registry/sensors_registry:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/registry/sensors_registry \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/registry/sensors_settings:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/registry/sensors_settings \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/registry/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/sns_reg_config \
    vendor/lge/winglm/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/lge/winglm/proprietary/vendor/etc/wifi/GLOBAL/bdwlan.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/GLOBAL/bdwlan.bin \
    vendor/lge/winglm/proprietary/vendor/etc/wifi/GLOBAL/bdwlan_ch0.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/GLOBAL/bdwlan_ch0.bin \
    vendor/lge/winglm/proprietary/vendor/etc/wifi/GLOBAL/bdwlan_ch1.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/GLOBAL/bdwlan_ch1.bin \
    vendor/lge/winglm/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/lge/winglm/proprietary/vendor/firmware/a615_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a615_zap.b00 \
    vendor/lge/winglm/proprietary/vendor/firmware/a615_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a615_zap.b01 \
    vendor/lge/winglm/proprietary/vendor/firmware/a615_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a615_zap.b02 \
    vendor/lge/winglm/proprietary/vendor/firmware/a615_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a615_zap.elf \
    vendor/lge/winglm/proprietary/vendor/firmware/a615_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a615_zap.mdt \
    vendor/lge/winglm/proprietary/vendor/firmware/a619_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a619_gmu.bin \
    vendor/lge/winglm/proprietary/vendor/firmware/a620_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a620_zap.b00 \
    vendor/lge/winglm/proprietary/vendor/firmware/a620_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a620_zap.b01 \
    vendor/lge/winglm/proprietary/vendor/firmware/a620_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a620_zap.b02 \
    vendor/lge/winglm/proprietary/vendor/firmware/a620_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a620_zap.elf \
    vendor/lge/winglm/proprietary/vendor/firmware/a620_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a620_zap.mdt \
    vendor/lge/winglm/proprietary/vendor/firmware/a630_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_sqe.fw \
    vendor/lge/winglm/proprietary/vendor/firmware/a650_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_gmu.bin \
    vendor/lge/winglm/proprietary/vendor/firmware/a650_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_sqe.fw \
    vendor/lge/winglm/proprietary/vendor/firmware/a650_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_zap.b00 \
    vendor/lge/winglm/proprietary/vendor/firmware/a650_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_zap.b01 \
    vendor/lge/winglm/proprietary/vendor/firmware/a650_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_zap.b02 \
    vendor/lge/winglm/proprietary/vendor/firmware/a650_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_zap.elf \
    vendor/lge/winglm/proprietary/vendor/firmware/a650_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_zap.mdt \
    vendor/lge/winglm/proprietary/vendor/firmware/crbtfw32.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/crbtfw32.tlv \
    vendor/lge/winglm/proprietary/vendor/firmware/crnv32.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crnv32.bin \
    vendor/lge/winglm/proprietary/vendor/firmware/crnv32u.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crnv32u.bin \
    vendor/lge/winglm/proprietary/vendor/firmware/ipa_fws-timestamp:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws-timestamp \
    vendor/lge/winglm/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/lge/winglm/proprietary/vendor/firmware/tfa98xx_rev0.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx_rev0.cnt \
    vendor/lge/winglm/proprietary/vendor/lib64/camera/com.qti.sensormodule.s5k2la.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.s5k2la.bin \
    vendor/lge/winglm/proprietary/vendor/lib64/camera/com.qti.sensormodule.s5k3m5.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.s5k3m5.bin \
    vendor/lge/winglm/proprietary/vendor/lib64/camera/com.qti.sensormodule.s5kgd1_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.s5kgd1_front.bin \
    vendor/lge/winglm/proprietary/vendor/lib64/camera/com.qti.sensormodule.s5kgw1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.s5kgw1.bin \
    vendor/lge/winglm/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/lge/winglm/proprietary/vendor/lib64/camera/com.qti.tuned.s5k2la.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.s5k2la.bin \
    vendor/lge/winglm/proprietary/vendor/lib64/camera/com.qti.tuned.s5k3m5.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.s5k3m5.bin \
    vendor/lge/winglm/proprietary/vendor/lib64/camera/com.qti.tuned.s5kgd1_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.s5kgd1_front.bin \
    vendor/lge/winglm/proprietary/vendor/lib64/camera/com.qti.tuned.s5kgw1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.s5kgw1.bin \
    vendor/lge/winglm/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/lge/winglm/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/lge/winglm/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/lge/winglm/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin

PRODUCT_PACKAGES += \
    libpn557_fw \
    vendor.lge.hardware.motor@1.0 \
    vendor.qti.hardware.fingerprint@1.0 \
    com.qti.eeprom.s5k2la_zc5130 \
    com.qti.eeprom.s5k3m5_fm24c32d \
    com.qti.eeprom.s5kgd1_fm24c64d \
    com.qti.eeprom.s5kgw1_fm24c128d \
    com.qti.sensor.s5k2la \
    com.qti.sensor.s5k3m5 \
    com.qti.sensor.s5kgd1_front \
    com.qti.sensor.s5kgw1 \
    com.lge.node.camerasolution \
    com.lge.node.capturebokeh \
    com.lge.node.elvis \
    com.lge.node.emeta \
    com.lge.node.hdr \
    com.lge.node.hlapse \
    com.lge.node.lavis \
    com.lge.node.multiframe \
    com.lge.node.novis \
    com.lge.node.realtimebokeh \
    com.lge.node.warp \
    com.lge.stats.aec.esc \
    com.lge.stats.aec \
    com.lge.stats.af \
    com.lge.stats.af_core \
    com.lge.stats.awb \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swregistration \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    liblg_aec_param_s5k2la_binning_preview \
    liblg_aec_param_s5k2la_binning_video \
    liblg_aec_param_s5k2la_cine_video \
    liblg_aec_param_s5k2la_dual_rec \
    liblg_aec_param_s5k2la_hfr_120 \
    liblg_aec_param_s5k2la_hfr_240 \
    liblg_aec_param_s5k2la_hfr_60 \
    liblg_aec_param_s5k2la_night_lapse \
    liblg_aec_param_s5k2la_night_preview \
    liblg_aec_param_s5k2la_out_focus \
    liblg_aec_param_s5k2la_out_focus_video \
    liblg_aec_param_s5k2la_panorama \
    liblg_aec_param_s5k2la_preview \
    liblg_aec_param_s5k2la_sensor_hdr_auto_preview \
    liblg_aec_param_s5k2la_sensor_hdr_auto_video \
    liblg_aec_param_s5k2la_sensor_hdr_on_preview \
    liblg_aec_param_s5k2la_sensor_hdr_on_video \
    liblg_aec_param_s5k2la_steady_cam \
    liblg_aec_param_s5k2la_steady_cam_short_exp \
    liblg_aec_param_s5k2la_video \
    liblg_aec_param_s5k3m5_binning_preview \
    liblg_aec_param_s5k3m5_binning_video \
    liblg_aec_param_s5k3m5_cine_video \
    liblg_aec_param_s5k3m5_hfr_120 \
    liblg_aec_param_s5k3m5_hfr_240 \
    liblg_aec_param_s5k3m5_hfr_60 \
    liblg_aec_param_s5k3m5_night_lapse \
    liblg_aec_param_s5k3m5_night_preview \
    liblg_aec_param_s5k3m5_out_focus \
    liblg_aec_param_s5k3m5_out_focus_video \
    liblg_aec_param_s5k3m5_panorama \
    liblg_aec_param_s5k3m5_preview \
    liblg_aec_param_s5k3m5_sensor_hdr_auto_preview \
    liblg_aec_param_s5k3m5_sensor_hdr_auto_video \
    liblg_aec_param_s5k3m5_sensor_hdr_on_preview \
    liblg_aec_param_s5k3m5_sensor_hdr_on_video \
    liblg_aec_param_s5k3m5_steady_cam \
    liblg_aec_param_s5k3m5_video \
    liblg_aec_param_s5kgd1_front_32M_preview \
    liblg_aec_param_s5kgd1_front_cine_video \
    liblg_aec_param_s5kgd1_front_dual_rec \
    liblg_aec_param_s5kgd1_front_hfr_240 \
    liblg_aec_param_s5kgd1_front_out_focus \
    liblg_aec_param_s5kgd1_front_out_focus_video \
    liblg_aec_param_s5kgd1_front_preview \
    liblg_aec_param_s5kgd1_front_sensor_hdr_auto_preview \
    liblg_aec_param_s5kgd1_front_sensor_hdr_auto_video \
    liblg_aec_param_s5kgd1_front_sensor_hdr_on_preview \
    liblg_aec_param_s5kgd1_front_sensor_hdr_on_video \
    liblg_aec_param_s5kgd1_front_video \
    liblg_aec_param_s5kgw1_64M_preview \
    liblg_aec_param_s5kgw1_binning_preview \
    liblg_aec_param_s5kgw1_binning_video \
    liblg_aec_param_s5kgw1_cine_8k_video \
    liblg_aec_param_s5kgw1_cine_video \
    liblg_aec_param_s5kgw1_cropzoom \
    liblg_aec_param_s5kgw1_hfr_120 \
    liblg_aec_param_s5kgw1_hfr_240 \
    liblg_aec_param_s5kgw1_hfr_480 \
    liblg_aec_param_s5kgw1_hfr_60 \
    liblg_aec_param_s5kgw1_night_lapse \
    liblg_aec_param_s5kgw1_night_preview \
    liblg_aec_param_s5kgw1_out_focus \
    liblg_aec_param_s5kgw1_out_focus_video \
    liblg_aec_param_s5kgw1_panorama \
    liblg_aec_param_s5kgw1_preview \
    liblg_aec_param_s5kgw1_sensor_hdr_auto_4k_video \
    liblg_aec_param_s5kgw1_sensor_hdr_auto_8k_video \
    liblg_aec_param_s5kgw1_sensor_hdr_auto_cropzoom \
    liblg_aec_param_s5kgw1_sensor_hdr_auto_preview \
    liblg_aec_param_s5kgw1_sensor_hdr_auto_video \
    liblg_aec_param_s5kgw1_sensor_hdr_on_cropzoom \
    liblg_aec_param_s5kgw1_sensor_hdr_on_preview \
    liblg_aec_param_s5kgw1_sensor_hdr_on_video \
    liblg_aec_param_s5kgw1_steady_cam \
    liblg_aec_param_s5kgw1_video \
    liblg_awb_param_s5k2law_night \
    liblg_awb_param_s5k2law_preview \
    liblg_awb_param_s5k2law_video0 \
    liblg_awb_param_s5k2law_video1 \
    liblg_awb_param_s5k2law_video10 \
    liblg_awb_param_s5k2law_video2 \
    liblg_awb_param_s5k2law_video3 \
    liblg_awb_param_s5k2law_video4 \
    liblg_awb_param_s5k2law_video5 \
    liblg_awb_param_s5k2law_video6 \
    liblg_awb_param_s5k2law_video7 \
    liblg_awb_param_s5k2law_video8 \
    liblg_awb_param_s5k2law_video9 \
    liblg_awb_param_s5k3m5w_night \
    liblg_awb_param_s5k3m5w_preview \
    liblg_awb_param_s5k3m5w_video0 \
    liblg_awb_param_s5k3m5w_video1 \
    liblg_awb_param_s5k3m5w_video10 \
    liblg_awb_param_s5k3m5w_video2 \
    liblg_awb_param_s5k3m5w_video3 \
    liblg_awb_param_s5k3m5w_video4 \
    liblg_awb_param_s5k3m5w_video5 \
    liblg_awb_param_s5k3m5w_video6 \
    liblg_awb_param_s5k3m5w_video7 \
    liblg_awb_param_s5k3m5w_video8 \
    liblg_awb_param_s5k3m5w_video9 \
    liblg_awb_param_s5kgd1f_night \
    liblg_awb_param_s5kgd1f_preview \
    liblg_awb_param_s5kgd1f_video0 \
    liblg_awb_param_s5kgd1f_video1 \
    liblg_awb_param_s5kgd1f_video10 \
    liblg_awb_param_s5kgd1f_video2 \
    liblg_awb_param_s5kgd1f_video3 \
    liblg_awb_param_s5kgd1f_video4 \
    liblg_awb_param_s5kgd1f_video5 \
    liblg_awb_param_s5kgd1f_video6 \
    liblg_awb_param_s5kgd1f_video7 \
    liblg_awb_param_s5kgd1f_video8 \
    liblg_awb_param_s5kgd1f_video9 \
    liblg_awb_param_s5kgw1n_crop \
    liblg_awb_param_s5kgw1n_night \
    liblg_awb_param_s5kgw1n_preview \
    liblg_awb_param_s5kgw1n_video0 \
    liblg_awb_param_s5kgw1n_video1 \
    liblg_awb_param_s5kgw1n_video10 \
    liblg_awb_param_s5kgw1n_video2 \
    liblg_awb_param_s5kgw1n_video3 \
    liblg_awb_param_s5kgw1n_video4 \
    liblg_awb_param_s5kgw1n_video5 \
    liblg_awb_param_s5kgw1n_video6 \
    liblg_awb_param_s5kgw1n_video7 \
    liblg_awb_param_s5kgw1n_video8 \
    liblg_awb_param_s5kgw1n_video9 \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs \
    com.qti.feature2.hdr \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.rt \
    com.qti.feature2.serializer \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    camera.lito \
    com.qti.chi.override \
    fingerprint.lito \
    vendor.lge.hardware.sensors.devicecontext@1.0-impl \
    lib.com.lge.elvis \
    libCmcPdaf \
    libCmcPdaf_tele \
    libRbsFlow \
    libSJVideoNR \
    libSNPE \
    libSRIyuv \
    libarcsoft_beauty_picselfie \
    libarcsoft_dualcam_portraitlighting \
    libarcsoft_dualcam_refocus \
    libarcsoft_dualcam_refocus_front \
    libarcsoft_dualcam_refocus_rear_t \
    libarcsoft_makeup \
    libarcsoft_object_tracking \
    libarcsoft_picselfie_algorithm \
    libarcsoft_singlecam_portrait_lighting \
    libbitmlengine \
    libbwfocuspeaking \
    libc++_shared \
    libcamera_nn_stub \
    libcamxexternalformatutils \
    libcamxfacialfeatures \
    libcamxfdalgo \
    libcamxfdengine \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxncs \
    libcamxstatscore \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libchilog \
    libcom.qti.chinodeutils \
    libdepthmapdecoder.arcsoft \
    libets_teeclient_v2 \
    libfilm_emulation_hal \
    libfpsph \
    libipebpsstriping \
    liblgae_main \
    liblgawb_main \
    liblgdnnsnpe \
    liblghdri \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmorpho_image_stab31 \
    libmorpho_wdr2 \
    libmpbase \
    libofflinelog \
    libprmclient \
    libremosaic_wrapper \
    libsns_device_context_prox \
    libsymphony-cpu \
    vendor.lge.hardware.sensors.devicecontext@1.0 \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor.qti.hardware.seccam@1.0 \
    vendor_lib_rfsa_adsp_AlacDecoderModule_so_1 \
    vendor_lib_rfsa_adsp_ApeDecoderModule_so_1 \
    vendor_lib_rfsa_adsp_AudioContextDetection_so_1 \
    vendor_lib_rfsa_adsp_AudioSphereModule_so_1 \
    vendor_lib_rfsa_adsp_CFCMModule_so_1 \
    vendor_lib_rfsa_adsp_EtsiAmrWbPlusDecModule_so_1 \
    vendor_lib_rfsa_adsp_EtsiEaacPlusEncAndCmnModule_so_1 \
    vendor_lib_rfsa_adsp_FlacDecoderModule_so_1 \
    vendor_lib_rfsa_adsp_HeaacDecoderModule_so_1 \
    vendor_lib_rfsa_adsp_LdacModule_so_1 \
    vendor_lib_rfsa_adsp_MIC2AMBModule_so_1 \
    vendor_lib_rfsa_adsp_SAPlusCmnModule_so_1 \
    vendor_lib_rfsa_adsp_SVACmnModule_so_1 \
    vendor_lib_rfsa_adsp_VoiceWakeup_V2_Module_so_1 \
    vendor_lib_rfsa_adsp_VorbisDecoderModule_so_1 \
    vendor_lib_rfsa_adsp_WmaProDecoderModule_so_1 \
    vendor_lib_rfsa_adsp_WmaStdDecoderModule_so_1 \
    vendor_lib_rfsa_adsp_capi_v2_aptX_CLHDADV_Encoder_so \
    vendor_lib_rfsa_adsp_capi_v2_aptX_CLHDAD_Speech_Decoder_so \
    vendor_lib_rfsa_adsp_fastrpc_shell_0 \
    vendor_lib_rfsa_adsp_ffns_module_fv9_so_1 \
    vendor_lib_rfsa_adsp_ffv_module_fv9_so_1 \
    vendor_lib_rfsa_adsp_ffv_module_fvx_so_1 \
    vendor_lib_rfsa_adsp_fluence_bs_module_fv9_so_1 \
    vendor_lib_rfsa_adsp_fluence_bs_module_fvx_so_1 \
    vendor_lib_rfsa_adsp_fluence_ef_module_fv9_so_1 \
    vendor_lib_rfsa_adsp_fluence_ef_module_fvx_so_1 \
    vendor_lib_rfsa_adsp_fluence_nn_module_fvx_so_1 \
    vendor_lib_rfsa_adsp_fluence_pro_vc_module_fv9_so_1 \
    vendor_lib_rfsa_adsp_fluence_pro_vc_module_fvx_so_1 \
    vendor_lib_rfsa_adsp_fluence_pro_vr_module_fv9_so_1 \
    vendor_lib_rfsa_adsp_fluence_pro_vr_module_fvx_so_1 \
    vendor_lib_rfsa_adsp_fluence_sm_module_fv9_so_1 \
    vendor_lib_rfsa_adsp_fluence_sm_module_fvx_so_1 \
    vendor_lib_rfsa_adsp_fluence_voiceplus_module_so_1 \
    vendor_lib_rfsa_adsp_libapps_mem_heap_so \
    vendor_lib_rfsa_adsp_libarcsoft_dualcam_refocus_skel_so \
    vendor_lib_rfsa_adsp_libbitml_nsp_skel_so \
    vendor_lib_rfsa_adsp_libcamera_nn_skel_so \
    vendor_lib_rfsa_adsp_libcvpdsp_skel_so \
    vendor_lib_rfsa_adsp_libdspCV_skel_so \
    vendor_lib_rfsa_adsp_libdsp_streamer_binning_so \
    vendor_lib_rfsa_adsp_libfastcvadsp_so \
    vendor_lib_rfsa_adsp_libfastcvdsp_skel_so \
    vendor_lib_rfsa_adsp_libhexagon_nn_skel_so \
    vendor_lib_rfsa_adsp_libscveObjectSegmentation_skel_so \
    vendor_lib_rfsa_adsp_libscveT2T_skel_so \
    vendor_lib_rfsa_adsp_libsns_device_context_skel_so \
    vendor_lib_rfsa_adsp_libsns_device_mode_skel_so \
    vendor_lib_rfsa_adsp_libsns_low_lat_stream_skel_so \
    vendor_lib_rfsa_adsp_libstabilitydomain_skel_so \
    vendor_lib_rfsa_adsp_libsysmon_skel_so \
    vendor_lib_rfsa_adsp_libsysmondomain_skel_so \
    vendor_lib_rfsa_adsp_libsysmonquery_skel_so \
    vendor_lib_rfsa_adsp_mm_fluence_sb_module_so_1 \
    vendor_lib_rfsa_adsp_mm_fluence_sb_module_fvx_so_1 \
    vendor_lib_rfsa_adsp_mmecns_module_so_1 \
    vendor_lib_rfsa_adsp_sm_fluence_sb_module_so_1 \
    vendor_lib_rfsa_adsp_sm_fluence_sb_module_fvx_so_1 \
    vendor_lib_rfsa_adsp_smecns_v2_module_fv9_so_1 \
    vendor_lib_rfsa_adsp_smecns_v2_module_fvx_so_1 \
    vendor_lib_rfsa_adsp_sns_bring_to_ear_so \
    vendor.lge.hardware.sensors.devicecontext@1.0-service.xml \
    vendor.lge.hardware.motor@1.0-service-popupcam \
    vendor.lge.hardware.sensors.devicecontext@1.0-service

PRODUCT_PACKAGES += \
    vendor_firmware_wlan_qca_cld_bdwlan_bin \
    vendor_firmware_wlan_qca_cld_bdwlan_ch0_bin \
    vendor_firmware_wlan_qca_cld_bdwlan_ch1_bin
